# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-13 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0003_auto_20170813_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=50)),
                ('msg', models.CharField(max_length=200)),
                ('msg_pic', models.ImageField(blank=True, upload_to='group_pic')),
            ],
        ),
    ]
