# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-13 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0004_discussion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(max_length=200),
        ),
    ]
