# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-13 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0005_auto_20170813_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='stat_id',
            field=models.IntegerField(default=0),
        ),
    ]
