# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-13 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0006_status_stat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_id', models.IntegerField(default=0)),
            ],
        ),
    ]
