# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-13 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0007_statusid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatusID',
        ),
    ]
