# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-21 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0008_delete_statusid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(max_length=128),
        ),
    ]
