# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-21 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0009_auto_20170821_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='subject',
        ),
    ]
