# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-05 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0010_remove_message_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='message',
            name='reciever',
            field=models.CharField(max_length=128),
        ),
    ]
