# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-07 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0011_auto_20170905_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
